// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unifye.Data;

#nullable disable

namespace Unifye.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
        modelBuilder.HasDefaultSchema("development");

        modelBuilder.Entity("Unifye.Models.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("users", "development");
            });

        modelBuilder.Entity("Unifye.Models.UserInterest", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Interest")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<Guid>("UserProfileId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("UserProfileId");

                b.ToTable("user_interests", "development");
            });

        modelBuilder.Entity("Unifye.Models.UserMatch", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("UserOneId")
                    .HasColumnType("uuid");

                b.Property<Guid>("UserTwoId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("UserOneId", "UserTwoId")
                    .IsUnique();

                b.ToTable("user_matches", "development");
            });

        modelBuilder.Entity("Unifye.Models.UserProfile", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.Property<DateOnly>("DateOfBirth")
                    .HasColumnType("date");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("Gender")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("ImageUrl")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.HasKey("UserId");

                b.ToTable("user_profiles", "development");
            });

        modelBuilder.Entity("Unifye.Models.UserSwipe", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsLiked")
                    .HasColumnType("boolean");

                b.Property<Guid>("SourceUserId")
                    .HasColumnType("uuid");

                b.Property<Guid>("TargetUserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("SourceUserId", "TargetUserId")
                    .IsUnique();

                b.ToTable("user_swipes", "development");
            });

        modelBuilder.Entity("Unifye.Models.UserInterest", b =>
            {
                b.HasOne("Unifye.Models.UserProfile", "UserProfile")
                    .WithMany("Interests")
                    .HasForeignKey("UserProfileId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("UserProfile");
            });

        modelBuilder.Entity("Unifye.Models.UserProfile", b =>
            {
                b.HasOne("Unifye.Models.User", "User")
                    .WithOne("Profile")
                    .HasForeignKey("Unifye.Models.UserProfile", "UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Unifye.Models.User", b =>
            {
                b.Navigation("Profile");
            });

        modelBuilder.Entity("Unifye.Models.UserProfile", b =>
            {
                b.Navigation("Interests");
            });
#pragma warning restore 612, 618
    }
}
